#### Stage , use the compiled app, ready for production with Nginx
FROM nginx

# Copy the angular build from Stage 1
COPY /distt/crudtuto-Front/ /usr/share/nginx/html

# Copy our custom nginx config
COPY /nginx-custom.conf /etc/nginx/conf.d/default.conf


# Expose port 80 to the Docker host, so we can access it 
# from the outside.
EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]

